---
name: Build
'on':
  push:
    branches:
    - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: 1.15.8
    steps:
    - name: Configure AWS Credentials via Static Keys
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Terraform CI
      uses: akerl/.github/actions/base-terraform@main
      with:
        tf_is_workspace: true
    - name: Post to hook-exporter
      uses: akerl/.github/actions/hook-exporter@main
      with:
        token: ${{ secrets.EXPORTER_TOKEN }}
        status: ${{ job.status }}
      if: always() && github.ref == 'refs/heads/main'
